services:
  - type: web
    name: careersync-mvp-final-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://careersync-mvp-final-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 