import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { User, Mail, Lock, Check } from 'lucide-react';
import PageTransition from '@/components/ui-components/PageTransition';
import GlassCard from '@/components/ui-components/GlassCard';
import Button from '@/components/ui-components/Button';
import Input from '@/components/ui-components/Input';
import GoogleButton from '@/components/ui-components/GoogleButton';
import Navbar from '@/components/layout/Navbar';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { GoogleLogin } from '@react-oauth/google';

const Signup = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();

  // Redirect if already authenticated
  useEffect(() => {
    if (isAuthenticated) {
      navigate('/dashboard');
    }
  }, [isAuthenticated, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!name || !email || !password) {
      toast.error('Please fill in all fields');
      return;
    }
    
    if (password.length < 8) {
      toast.error('Password must be at least 8 characters long');
      return;
    }
    
    setIsLoading(true);
    
    try {
      // Create a user object with the form data
      const userData = {
        id: '1', // In a real app, this would be generated by the backend
        name,
        email,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`
      };
      
      // In a real app, you would register the user here
      await login(userData);
      toast.success('Account created successfully!');
      navigate('/dashboard');
    } catch (error) {
      console.error('Registration error:', error);
      toast.error('Failed to create account. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGoogleSuccess = async (response) => {
    try {
      console.log('Google signup response:', response);
      
      // Parse the JWT token from credential
      const token = response.credential;
      console.log('Got credential token:', token);
      
      // Decode the JWT token properly
      const base64Url = token.split('.')[1];
      const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
      const decodedToken = JSON.parse(window.atob(base64));
      
      console.log('Decoded Google token:', decodedToken);
      
      const userData = {
        id: decodedToken.sub,
        name: decodedToken.name,
        email: decodedToken.email,
        avatar: decodedToken.picture // Always include the picture URL
      };
      
      console.log('User data extracted from Google:', userData);
      
      // Log in with the user data
      await login(userData);
      toast.success(`Welcome, ${userData.name}!`);
      navigate('/dashboard');
    } catch (error) {
      console.error('Google login error:', error);
      toast.error('Failed to log in with Google. Please try again.');
    }
  };
  
  const handleGoogleFailure = () => {
    toast.error('Google login failed. Please try again.');
  };

  const handleGoogleSignup = async () => {
    setIsLoading(true);
    
    try {
      await login();
      toast.success('Account created with Google successfully!');
      navigate('/dashboard');
    } catch (error) {
      console.error('Google signup error:', error);
      toast.error('Failed to create account with Google. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };


  return (
    <PageTransition>
      <div className="min-h-screen bg-gradient-to-b from-blue-light/20 to-background">
        <Navbar />
        
        <div className="container mx-auto px-4 md:px-6 pt-32 pb-20">
          <div className="max-w-md mx-auto">
            <GlassCard>
              <div className="text-center mb-8">
                <h1 className="text-2xl font-bold mb-2">Create an Account</h1>
                <p className="text-muted-foreground">
                  Join CareerSync AI to streamline your job search
                </p>
              </div>
              
              <form onSubmit={handleSubmit} className="space-y-4">
                <Input
                  label="Full Name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="John Doe"
                  required
                />
                
                <Input
                  label="Email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  required
                />
                
                <Input
                  label="Password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Create a password"
                  required
                />
                
                <div className="text-sm text-muted-foreground">
                  <p className="flex items-center gap-1 mb-1">
                    <Check className="h-4 w-4 text-blue" />
                    <span>At least 8 characters</span>
                  </p>
                </div>
                
                <Button 
                  type="submit" 
                  className="w-full"
                  isLoading={isLoading}
                >
                  Create Account
                </Button>
              </form>
              
              <div className="relative my-6">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-border"></div>
                </div>
                <div className="relative flex justify-center text-xs">
                  <span className="px-2 bg-card text-muted-foreground">Or continue with</span>
                </div>
              </div>
              
              <div className="flex justify-center">
                <GoogleButton />
                {/* Hidden Google login button - will be triggered by our custom button */}
                <div className="hidden">
                  <GoogleLogin onSuccess={handleGoogleSuccess} onError={handleGoogleFailure} />
                </div>
              </div>
              
              <p className="text-center mt-6 text-sm text-muted-foreground">
                Already have an account?{' '}
                <Link to="/login" className="text-blue hover:underline">
                  Sign in
                </Link>
              </p>
            </GlassCard>
          </div>
        </div>
      </div>
    </PageTransition>
  );
};

export default Signup;